alias mkdir='mkdir -p'
alias matlab='~/.scripts/matlab.sh'
alias maple='~/opt/maple18/bin/xmaple'
alias cp_p='rsync -r -v --progress'
alias pdfshrink='~/.scripts/pdfshrink.sh'
alias pdfsearch='~/.scripts/pdfsearch'
alias mergepdf='~/.scripts/pdfmerge'
alias pdfmerge='~/.scripts/pdfmerge'
alias pdfcrop='~/.scripts/pdfcrop.pl'
alias pacman='pacaur -r'
alias cemacs='emacs -nw'
alias remacs='sudo emacs -nw'
alias srm='~/.scripts/srm.sh'
alias mplayerdir='mplayer -playlist <(find "$PWD" -type f)'
alias ls="ls --color"
alias grep="grep --colour"
alias clip2prim="xclip -o -selection clipboard | xclip -i -selection primary"
alias prim2clip="xclip -o -selection primary | xclip -i -selection clipboard"
alias noscreensleep="xset -dpms; xset s off"
alias backlight="~/.scripts/backlight.sh"
alias cleanlatex="~/.scripts/cleanlatex.sh"
alias surm="sudo rm"
alias sumv="sudo mv"
alias sucat="sudo cat"
